analisar_experts:
  description: >
    Diga tudo que um expert sobre {topic} é capaz de fazer.
    Diga que é preciso para ser um exepert sobre {topic}
    Diga sobre quais representações mentais um expert sobre {topic} tem 
    e o que diferencia ele de pessoas não experts sobre {topic}
    Entenda a diferença entre um bom sobre {topic} e um expert sobre {topic}
  expected_output: >
    Informações sobre tudo que um expert sobre {topic} é capaz de realizar.
    O que diferencia o expert de {topic} de alguem apenas bom sobre {topic}
  agent: expert

plano_estudos:
  description: >
    Crie atividade e plano de estudo de prática deliberada 
    para o usuário se torna um expert sobre {topic} entendo o quem são os experts
    e o que eles são capaz de fazer. Sempre aplicando principios de pratica deliberada
    Atividades para criar representações mentais como as dos especislitas.
  expected_output: >
    Uma lista de atividade do básico até o avançado aplicando princípios de prática deliberada
    em função do usuário ao seguir a lista aprender e ser um expert
  agent: professor_expert


organiza_estudos:
  description: >
    Organiza os estudos diários do usuário a partir do objetivo.
    Entende as atividade necessárias e cria divida as tarefaz 
    em horário específicos
    Aplica a prática deliberada na criação dessa subtarefaz
    Diz o o que usuário tem que validar no final de cada tarefa 
  expected_output: >
    Retorna uma lista de tarefaz e sessões. Dizendo qual resultado
    final o usuário tem que ter após cada sessão.
  agent: organiza_tarefaz


instrucoes_coach:
  description: >
    Recebe uma lista de atiidades e cria instrucoes de
    forma imperativa para que o usuário realize as atividades.
    Usando aspectos de prática deliberada para impulsionar 
    o usuário a sair da zona de conforto enquanto 
    motiva e acompanha a realização das tarefaz. 
    O objetivo: {objetivo}
    Entendo a hora de incio {hr_inicio}
    e hora fim {hr_fim}
  expected_output: >
    Uma lista de mensagens, como se fosse frases imperativas do coach
    que irá acompanhar o desenvolvimento do usuário e irá motivar.
    Ache pontos durante a mensagens para realizar enviar essas 
    mensagens. Dizendo melhor o que o usuário precisava 
    fazer ele precisa se concentrar
  agent: coach