analisar_experts:
  description: >
    Diga tudo que um expert sobre {topic} é capaz de fazer.
    Diga que é preciso para ser um exepert sobre {topic}
    Diga sobre quais representações mentais um expert sobre {topic} tem 
    e o que diferencia ele de pessoas não experts sobre {topic}
    Entenda a diferença entre um bom sobre {topic} e um expert sobre {topic}
  expected_output: >
    Informações sobre tudo que um expert sobre {topic} é capaz de realizar.
    O que diferencia o expert de {topic} de alguem apenas bom sobre {topic}
  agent: expert

plano_estudos:
  description: >
    Crie atividade e plano de estudo de prática deliberada 
    para o usuário se torna um expert sobre {topic} entendo o quem são os experts
    e o que eles são capaz de fazer. Sempre aplicando principios de pratica deliberada
  expected_output: >
    Uma lista de atividade do básico até o avançado aplicando princípios de prática deliberada
    em função do usuário ao seguir a lista aprender e ser um expert
  agent: professor_expert
